name: build-and-test

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'images/**'
      - 'LICENSE'
      - 'SUNDIALS_LICENSE'
      - '.github/ISSUE_TEMPLATE/**'

  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'images/**'
      - 'LICENSE'
      - 'SUNDIALS_LICENSE'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  lint:
    name: (Lint ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    defaults:
      run: 
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Spell check
        run: |
          pip install codespell
          codespell --config .github/linters/.codespellrc
          
      - name: Code format
        run: |
          pip install flake8
          flake8 --config .github/linters/.flake8 src
          flake8 --config .github/linters/.flake8 tests

  test:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.13']
        
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda/python
        uses: conda-incubator/setup-miniconda@v3
        with:  # ci_environment.yml specifies sundials version to compile
          auto-update-conda: true
          miniconda-version: latest
          environment-file: environments/ci_environment.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: sun

      - name: Verify environment
        run: |
          conda info
          conda list

      - name: Install scikit-sundae
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: List info
        run: |
          conda info
          conda list
                
      - name: Pytest
        run: |
          pip install pandas pytest
          pytest .
