name: build-and-test

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.txt'
      - 'README*'
      - 'CHANGELOG*'
      - 'docs/*'
      - 'images/*'
      - '.github/ISSUE_TEMPLATE/*'

  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.txt'
      - 'README*'
      - 'CHANGELOG*'
      - 'docs/*'
      - 'images/*'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  lint:
    name: (Lint ${{ matrix.python-version }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.12']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Spell check
        run: |
          pip install codespell
          codespell --config .github/linters/.codespellrc

  test:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.12']
        
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda/python
        uses: conda-incubator/setup-miniconda@v3
        with:
          channel-priority: true
          activate-environment: sun
          python-version: ${{ matrix.python-version }}
          miniconda-version: latest
          auto-update-conda: true

      - name: Conda dependencies  # Set SUNDIALS version to build/test against
        run: |
          conda install sundials=7.1 -c conda-forge

      - name: Install scikit-sundae
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: List info
        run: |
          conda info
          conda list
                
      - name: Pytest
        run: |
          pip install pandas pytest
          pytest .
